# HTTP REST interface
rest: true

# GraphQL schemas for database/tables/attributes
graphqlSchema:
  files: "./src/models/user.graphql"

# Loads JavaScript modules
jsResource:
  files: "./src/controllers/resources.ts"
